version: "2.1"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
  flyway:
    image: boxfuse/flyway
    depends_on:
      - db
    command: -configFiles=/flyway/conf/flyway.conf -url=${POSTGRES_CONNECTION_STR} -user=${POSTGRES_USER} -password=${POSTGRES_PASSWORD} migrate
    volumes:
      - ${PWD}/db/migration:/flyway/sql
      - ${PWD}/db/docker-flyway:/flyway/conf
      - ${PWD}/db/docker-driver:/flyway/drivers
    links:
      - "db:${POSTGRES_HOST_ALIAS}"
  backend:
    build:
      context: .
    command: bin/app
    env_file:
      - .env
    depends_on:
      - db
      - flyway
    links:
      - "db:${POSTGRES_HOST_ALIAS}"
    ports:
      - "80:${SERVER_PORT}"